models/User.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property integer $user_id
 * @property string $name
 * @property string $email
 * @property integer $company_id
 *
 * @property Company $company
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'email', 'company_id'], 'required'],
            [['company_id'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['email'], 'string', 'max' => 70],
            [['email'], 'email'],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => Company::className(), 'targetAttribute' => ['company_id' => 'company_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'user_id' => 'User ID',
            'name' => 'Name',
            'email' => 'Email',
            'company_id' => 'Company',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(Company::className(), ['company_id' => 'company_id']);
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\TransferLog;
use Yii;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\data\ArrayDataProvider;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => User::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $success = true;
            return json_encode($success);
        } else {
            return $this->renderPartial('_form', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $success = true;
            return json_encode($success);
        } else {
            return $this->renderPartial('_form', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Render form
     * @return string
     */
    public function actionForm($id = 0)
    {
        if ($id > 0) {
            $model = $this->findModel($id);
        } else {
            $model = new User();
        }


        return $this->renderPartial('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        TransferLog::deleteAll(['user_id' => $id]);
        $model->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * @return string
     */
    public function actionAbuser()
    {

        return $this->render('abuser', [

        ]);
    }

    /**
     * @return string
     */
    public function actionReport($d)
    {
        $d = date('m',strtotime($d));
        $dataProvider = new ArrayDataProvider([
            'allModels' => TransferLog::findBySql('SELECT * FROM (SELECT `transferred`, `name`, `quota`, create_date FROM `transfer_log` 
                                                   LEFT JOIN `company` ON transfer_log.company_id=company.company_id WHERE MONTH(FROM_UNIXTIME(`create_date`))='.$d.'
                                                   GROUP BY MONTH(FROM_UNIXTIME(`create_date`)), transfer_log.`company_id`) s 
                                                   WHERE s.transferred > s.quota ORDER BY s.transferred DESC')->asArray()->all(),
            'sort' => false

        ]);
        return $this->renderPartial('grid-transfer', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionGenerate()
    {
        $time = strtotime(date('Y-m-d'));
        $allUser = User::find()->select('user_id, company_id')->asArray()->all();
        $maxUser = count($allUser) - 1;
        $lastTime = $time-3600*24*180;
        $f = true;
        do {
            $count = rand(3, 6);
            for ($i = 0; $i < $count; $i++) {
                $u = $allUser[rand(0, $maxUser)];
                $t = new TransferLog();
                $rb = rand(100, 10995116277760);
                $t->company_id = $u['company_id'];
                $t->user_id = $u['user_id'];
                $t->create_date = rand($time, ($time + 3600 * 23));
                $t->transferred = $rb;
                $t->resourced = 'http://test.com/' . md5($rb);
                $t->save();
            }
            $time -= 3600 * 24;
            if ($time < $lastTime) {
                $f = false;
            }
        } while ($f);
        $success = true;
        return json_encode($success);
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(['options' => ['class' => 'user-form'], 'enableAjaxValidation' => true,]); ?>
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'company_id')->dropDownList(\app\models\Company::getAllCompany()) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/abuser.php
<?php

use yii\bootstrap\Modal;
use yii\grid\DataColumn;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $model \app\models\User */

$this->title = 'AbUsers';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="user-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>
        <input type='text' id='txtDate' />
        <?= Html::a('Show report', '', ['class' => 'btn btn-success show-report']) ?>
        <?= Html::a('Generate date', '', ['class' => 'btn btn-success generate-trafic']) ?>
        <div class="loader" style="display: none"></div>

    </p>
    <div class="report-view">
    </div>
</div>
<script type="application/javascript">
    window.addEventListener('load', function () {

        $('.generate-trafic').click(function(event){
            event.preventDefault();
            $('.loader').show();
            $(this).hide();
            var url = '/user/generate';
            $.ajax({
                url: url,
                type: "GET",
                data: {},
                success: function (data) {
                    $('.loader').hide();
                    $('.generate-trafic').show();
                }
            });
        });
        $('.show-report').click(function(event){
            event.preventDefault();
            var d = $('#txtDate').val();
            if( d==''){
                alert('Choice date!');
                return false;
            }

            var url = '/user/report?d='+d;
            $.ajax({
                url: url,
                type: "GET",
                data: {},
                success: function (data) {

                    $('.report-view').html(data);

                }
            });
        });
        $('#txtDate').datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: 'MM yy',

            onClose: function() {
                var iMonth = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var iYear = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).datepicker('setDate', new Date(iYear, iMonth, 1));
            },

            beforeShow: function() {
                if ((selDate = $(this).val()).length > 0)
                {
                    iYear = selDate.substring(selDate.length - 4, selDate.length);
                    iMonth = jQuery.inArray(selDate.substring(0, selDate.length - 5), $(this).datepicker('option', 'monthNames'));
                    $(this).datepicker('option', 'defaultDate', new Date(iYear, iMonth, 1));
                    $(this).datepicker('setDate', new Date(iYear, iMonth, 1));
                }
            }
        });

    }, false);
</script>

views/user/grid-transfer.php
<?php

use app\models\Quota;
use yii\grid\DataColumn;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>

<?php Pjax::begin(); ?>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

        [
            'attribute' => 'name',
            'value' => function ($model) {
                return $model['name'];
            }

        ],
//        [
//            'attribute' => 'date',
//            'value' => function ($model) {
//                return date('M',$model['create_date']);
//            }
//
//        ],
        'transferred'=> [
            'class' => DataColumn::className(),
            'attribute' => 'used',
            'format' => 'html',
            'value' => function ($model) {
                $qArr = Quota::getBigValue($model['transferred']);
                return $qArr[0].' '.Quota::$name[$qArr[1]];
            }
        ],
        'quota'=> [
            'class' => DataColumn::className(),
            'attribute' => 'quota',
            'format' => 'html',
            'value' => function ($model) {
                $qArr = Quota::getBigValue($model['quota']);
                return $qArr[0].' '.Quota::$name[$qArr[1]];
            }
        ],

        ],
    ]); ?>
<?php Pjax::end(); ?></div>

views/user/index.php
<?php

use yii\bootstrap\Modal;
use yii\grid\DataColumn;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $model \app\models\User */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create User', '', ['class' => 'btn btn-success add-user', 'onclick'=>"idUser=0"]) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'name',
            'email:email',
            'company_id'=> [
                'class' => DataColumn::className(),
                'attribute' => 'company_id',
                'format' => 'html',
                'value' => function ($model) {
                    return $model->company->name;
                }
            ],
            [
                'class' => \yii\grid\ActionColumn::className(),
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        return '<a href="" onclick="idUser='.$model->user_id.'" class="update-user" title="Update"><span class="glyphicon glyphicon-pencil"></span></a>';
                    },
                ],
                'template' => '{update}  {delete}',
            ]
        ],
    ]); ?>
<?php Pjax::end();
Modal::begin([
    'header' => '<h2>Create user</h2>',
    'id'=>"modalUser"
]);?>
<div class="modal-content">
    <div class="modal-body">
        ...
    </div>
</div>

<?php Modal::end();
?></div>
<script type="application/javascript">
    var idUser = 0;
    window.addEventListener('load', function () {
        $('.add-user, .update-user').click(function(event){
            event.preventDefault();
            var url = '/user/form?id='+idUser;
            var modalContainer = $('#modalUser');
            $.ajax({
                url: url,
                type: "GET",
                data: {},
                success: function (data) {
                    $('.modal-body').html(data);
                    if(idUser>0){
                        $('.modal-header h2').text('Update user');
                    }

                    modalContainer.modal({show:true});
                }
            });
        });
        $(document).on("submit", '.user-form', function (e) {
            e.preventDefault();
            var form = $(this);
            var url = "/user/create";
            if(idUser>0){
                url = '/user/update?id='+idUser;
            }

            $.ajax({
                url: url,
                type: "POST",
                data: form.serialize(),
                success: function (result) {
                    var modalContainer = $('#modalUser');
                    var modalBody = modalContainer.find('.modal-body');
                    if (result == 'true') {
                        modalBody.html("<div class='alert alert-success'>");
                        $('.alert-success').append("<strong>Success!</strong>");
                        $('.alert-success').append('</div>');
                        setTimeout(function() {
                            $("#modalUser").modal('hide');
                        }, 4000);
                        window.location.reload(false);

                    }
                    else {
                        modalBody.html(result).hide().fadeIn();
                    }
                }
            });
            return false;
        });
    }, false);
</script>