models/Company.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "company".
 *
 * @property integer $company_id
 * @property string $name
 * @property integer $quota
 */
class Company extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public $quotaName = 0;
    public static function tableName()
    {
        return 'company';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'quota', 'quotaName'], 'required'],
            [['quota', 'quotaName'], 'integer'],
            [['name'], 'string', 'max' => 100],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'company_id' => 'Company ID',
            'name' => 'Name',
            'quota' => 'Quota',
            'quotaName' => 'Type',
        ];
    }

    /**
     * Get all company
     * @return array
     */
    public static function getAllCompany()
    {
        return ArrayHelper::map(self::find()->select(['company_id', 'name'])->asArray()->all(), 'company_id', 'name');
    }
}

controllers/CompanyController.php
<?php

namespace app\controllers;

use app\models\Quota;
use app\models\TransferLog;
use app\models\User;
use Yii;
use app\models\Company;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CompanyController implements the CRUD actions for Company model.
 */
class CompanyController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Company models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Company::find(),
        ]);
        $model = new Company();

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model' => $model,
        ]);
    }


    /**
     * Creates a new Company model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Company();
        if($model->load(Yii::$app->request->post())) {
            $model->quota = Quota::getSmallValue($model->quota, $model->quotaName);
            Yii::trace($model->quota);
            if($model->save()){
                $success=true;
                return json_encode($success);
            }

        }
        return $this->renderPartial('_form', [
            'model' => $model,
        ]);

    }

    /**
     * Updates an existing Company model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if($model->load(Yii::$app->request->post())) {
            $model->quota = Quota::getSmallValue($model->quota, $model->quotaName);
            if($model->save()){
                $success=true;
                return json_encode($success);
            }
        }
        $qArr = Quota::getBigValue($model->quota);
        $model->quota = $qArr[0];
        $model->quotaName = $qArr[1];
        return $this->renderPartial('_form', [
            'model' => $model,
        ]);

    }


    /**
     * Render form
     * @return string
     */
    public function actionForm($id=0)
    {
        if($id>0){
            $model = $this->findModel($id);
            $qArr = Quota::getBigValue($model->quota);
            $model->quota = $qArr[0];
            $model->quotaName = $qArr[1];
        }else{
            $model = new Company();
        }


        return $this->renderPartial('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Company model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        TransferLog::deleteAll(['company_id'=>$id]);
        User::deleteAll(['company_id'=>$id]);
        $model->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Company model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Company the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Company::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/company/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Company */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="company-form">

    <?php $form = ActiveForm::begin(['options' => ['class' => 'company-form'], 'enableAjaxValidation' => true,]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'quota')->textInput() ?>

    <?= $form->field($model, 'quotaName')->dropDownList(\app\models\Quota::$name) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/company/index.php
<?php

use app\models\Quota;
use yii\bootstrap\Modal;
use yii\grid\DataColumn;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Companies';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="company-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Company', '', ['class' => 'btn btn-success add-company' ]) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'name',
            'quota'=> [
                'class' => DataColumn::className(),
                'attribute' => 'quota',
                'format' => 'html',
                'value' => function ($model) {
                    $qArr = Quota::getBigValue($model->quota);
                    return $qArr[0].' '.Quota::$name[$qArr[1]];
                }
            ],
            [
                'class' => \yii\grid\ActionColumn::className(),
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        return '<a href="" onclick="idCompany='.$model->company_id.'" class="update-company" title="Update"><span class="glyphicon glyphicon-pencil"></span></a>';
                    },



                ],
                'template' => '{update}  {delete}',
            ]
        ],
    ]); ?>
<?php Pjax::end();
Modal::begin([
    'header' => '<h2>Create company</h2>',
    'id'=>"modalCompany"
]);?>
    <div class="modal-content">
        <div class="modal-body">
            ...
        </div>
    </div>

<?php Modal::end();
?></div>
<script type="application/javascript">
    var idCompany = 0;
    window.addEventListener('load', function () {
        $('.add-company, .update-company').click(function(event){
            event.preventDefault();
            var url = '/company/form?id='+idCompany;
            var modalContainer = $('#modalCompany');
            $.ajax({
                url: url,
                type: "GET",
                data: {},
                success: function (data) {
                    $('.modal-body').html(data);
                    if(idCompany>0){
                        $('.modal-header h2').text('Update company');
                    }

                    modalContainer.modal({show:true});
                }
            });
        });
        $(document).on("submit", '.company-form', function (e) {
            e.preventDefault();
            var form = $(this);
            var url = "/company/create";
            if(idCompany>0){
                url = '/company/update?id='+idCompany;
            }

            $.ajax({
                url: url,
                type: "POST",
                data: form.serialize(),
                success: function (result) {
                    console.log(result);
                    var modalContainer = $('#modalCompany');
                    var modalBody = modalContainer.find('.modal-body');
                    if (result == 'true') {
                        modalBody.html("<div class='alert alert-success'>");
                        $('.alert-success').append("<strong>Success!</strong>");
                        $('.alert-success').append('</div>');
                        setTimeout(function() {
                            $("#modalCompany").modal('hide');
                        }, 4000);
                        window.location.reload(false);

                    }
                    else {
                        modalBody.html(result).hide().fadeIn();
                    }
                }
            });
            return false;
        });
    }, false);
</script>